In [3]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[3, 3, 7],
       [2, 0, 0],
       [8, 2, 4]], dtype=int32)

In [6]:
np.random.randn(30,30).mean()

np.float64(-0.06320673118730946)

In [10]:
np.std(data)

np.float64(2.615244954653293)

In [18]:
np.mean(data)

np.float64(3.2222222222222223)

In [19]:
np.median(data)

np.float64(3.0)

In [21]:
data=np.random.randint(0,100,10)
data

array([23, 94,  1, 22, 11, 93, 12, 63, 60,  6], dtype=int32)

In [22]:
data

array([23, 94,  1, 22, 11, 93, 12, 63, 60,  6], dtype=int32)

In [23]:
data.min()

np.int32(1)

In [24]:
data.max()

np.int32(94)

In [26]:
import numpy as np
data=np.random.randint(0,5,(3,3))
data

array([[4, 3, 1],
       [1, 0, 2],
       [0, 0, 0]], dtype=int32)

In [27]:
data.sum(axis=0)

array([5, 3, 3])

In [28]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[0, 1, 3],
       [9, 1, 0],
       [4, 1, 9]], dtype=int32)

In [30]:
data.max(axis=0)

array([9, 1, 9], dtype=int32)

In [31]:
data.min(axis=1)

array([0, 0, 1], dtype=int32)

In [33]:
import numpy as np
data = np.random.randint(1, 10,10)
data

array([2, 4, 9, 9, 6, 4, 4, 3, 1, 9], dtype=int32)

In [34]:
data

array([2, 4, 9, 9, 6, 4, 4, 3, 1, 9], dtype=int32)

In [38]:
data.argmax()

np.int64(2)

In [39]:
data

array([2, 4, 9, 9, 6, 4, 4, 3, 1, 9], dtype=int32)

In [41]:
data.argmin()+1

np.int64(9)

In [45]:
import numpy as np
data = np.random.randint(0, 1000, (3, 3))
data

array([[156, 626, 749],
       [773, 538, 880],
       [285, 445, 509]], dtype=int32)

In [46]:
data.argmax(axis=1)

array([2, 2, 2])

In [47]:
data.argmin(axis=1)

array([0, 1, 0])

In [49]:
data = np.random.randint(0, 10,(3,3))
data

array([[5, 5, 7],
       [6, 4, 3],
       [5, 4, 8]], dtype=int32)

In [50]:
x = np.random.randint(0, 10, (3, 3))
y = np.random.randint(0, 10, (1, 3))
x+y

array([[10, 10,  8],
       [10,  6,  6],
       [14,  5,  8]], dtype=int32)

In [51]:
x

array([[4, 5, 6],
       [4, 1, 4],
       [8, 0, 6]], dtype=int32)

In [52]:
y

array([[6, 5, 2]], dtype=int32)